# Generated by Django 4.1.5 on 2024-03-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='grapes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=30)),
                ('pemail', models.CharField(max_length=50)),
                ('property_code', models.CharField(max_length=20)),
                ('comments', models.CharField(max_length=19999)),
            ],
        ),
        migrations.CreateModel(
            name='loginn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='searchdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=30)),
                ('property_name', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=500)),
                ('code', models.CharField(max_length=20)),
                ('Aminites', models.CharField(max_length=500)),
                ('distance', models.CharField(max_length=500)),
                ('phone1', models.CharField(max_length=15)),
                ('phone2', models.CharField(max_length=15)),
                ('price', models.CharField(max_length=8)),
                ('prop_description', models.CharField(max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
